name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in repository
      run: |
        ls -la

    - name: Replace Secrets in JS
      run: |
        # Проверяем, существует ли файл script.js
        if [ ! -f script.js ]; then
          echo "Error: script.js not found!"
          exit 1
        fi

        # Проверяем, что все секреты предоставлены
        if [ -z "$CLIENT_ID_VALUE" ] || [ -z "$SPREADSHEET_ID_VALUE" ] || [ -z "$API_KEY_VALUE" ]; then
          echo "Error: One or more secrets are missing!"
          exit 1
        fi

        # Заменяем заполнители на реальные секреты
        sed -i "s@{{ GITHUB_SECRET_CLIENT_ID }}@$CLIENT_ID_VALUE@g" script.js
        sed -i "s@{{ GITHUB_SECRET_SPREADSHEET_ID }}@$SPREADSHEET_ID_VALUE@g" script.js
        sed -i "s@{{ GITHUB_SECRET_API_KEY }}@$API_KEY_VALUE@g" script.js

        # Проверяем, что замены прошли успешно
        if grep -q "{{ GITHUB_SECRET_"
